@GameStore_HostAddress = http://localhost:5137
@token = paste-login-token-here

GET {{GameStore_HostAddress}}/games

###
GET {{GameStore_HostAddress}}/games/2

###
POST {{GameStore_HostAddress}}/games
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Sonic Race",
  "genreId": 1,
  "price": 15.10,
  "releaseDate": "2021-11-15"
}

###
PUT {{GameStore_HostAddress}}/games/6
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Transformers: The Last Knight",
  "genreId": 4,
  "price": 25.99,
  "releaseDate": "2022-03-03"
}

###
DELETE {{GameStore_HostAddress}}/games/1
Authorization: Bearer {{token}}

###
GET {{GameStore_HostAddress}}/genres

###
GET {{GameStore_HostAddress}}/genres/1

###
POST {{GameStore_HostAddress}}/genres
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Racing"
}

###
PUT {{GameStore_HostAddress}}/genres/6
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Simulation"
}

###
DELETE {{GameStore_HostAddress}}/genres/6
Authorization: Bearer {{token}}
